<?php
/**
 * Udevix
 *
 * @author     UdevixTeam <udevix@gmail.com>
 * @copyright  Copyright (c) 2015 Udevix
 */
?>

<?php
$helper = Mage::helper('udevix_google_tag_manager');
if ($helper->isActive() && $helper->isActiveRemarketing()):
    $remarketingData = $this->getRemarketingData();
    ?>
    <?php if ($remarketingData !== false) : ?>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            try {
                dataLayer.push(<?php echo $remarketingData ?>);
            }
            catch (err) {
            }
        });
    </script>
<?php endif; ?>
<?php endif; ?>
