<?php
$helper = Mage::helper('itfellow_gtm');
if ($helper->isActive() && $helper->isReMarketingTagActive()) {
    $remarketingTagData = $this->getRemarketingTagData();
   if ($remarketingTagData !== false) { ?>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            try {
                dataLayer.push(<?php echo $remarketingTagData ?>);
            }
            catch (err) {
            }
        });
    </script>
<?php 
   }
} 
?>
